- hosts: localhost
  connection: local
  gather_facts: false

  tasks:

  - name: Determine public IP
    command: curl ifconfig.co
    register: my_ip

  - name: Terraform destroy
    terraform:
        project_path: "{{ playbook_dir }}"
        state: absent
    register: tfout

  - debug: var=tfout
